### ISSUE TITLE
Minimum PHP Version requirement is unclear

### ISSUE THREAD

**Issue by tstrijdhorst** [SebastianKersten/Mimoto#15]
Can you please add the minimum version of PHP you need to the composer requirements? This would help in deciding which environments it can run and which language constructs we can use for PRs.

For an example see:
https://github.com/tstrijdhorst/capetown/blob/master/composer.json#L15

**Comment by SebastianKersten** [comment]
Thanks! I've added a minimum of 5.6.0 now!
